# Number of Unique Paths

Given a M X N matrix with your initial position at top-left cell, find the number of possible unique paths to reach the bottom right cell of the matrix from the initial position.

Note: Possible moves can be either down or right at any point in time, i.e., we can move to matrix[i+1][j] or matrix[i][j+1] from matrix[i][j].

Input: 
The first line contains an integer T, depicting total number of test cases. Then following T lines contains an two integers N and M depicting the size of the grid.

In [43]:
import numpy

N = 3
M = 3

matrix = numpy.zeros(shape=(N,M))
matrix[0][0] = 1
matrix[N-1][M-1] = 1
print(matrix)
    
def unique_paths(N,M):
    
    if (N<=2 and M <= 2):
        return 2
    elif (N > 1 and M > 1):
        number_path = unique_paths(N-1,M)+unique_paths(N,M-1)
    else:
        return 1

    return number_path
    
                        

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]


In [44]:
unique_paths(N,M)

6